---
- block:
  - name: create service target directory
    file:
      path: "/var/www/{{ service_name }}"
      owner: root
      group: root
      state: directory
      mode: 0755

  - name: deploy service
    template:
      dest: "/var/www/{{ service_name }}/index.html"
      src: index.html
      owner: root
      group: root
      mode: 0644

  - name: update nginx config
    template:
      dest: "/etc/nginx/sites-available/default"
      src: default
      owner: root
      group: root
      mode: 0644

  become: true
  become_method: sudo
  tags:
    - app-config
